spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
